app = "mindmate-ai-backend"
primary_region = "otp"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
